services:
  app:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: pydigestor-app
    environment:
      - DATABASE_URL=sqlite:////app/data/pydigestor.db
    env_file:
      - ../.env
    volumes:
      - ../src:/app/src
      - ../tests:/app/tests
      - ../alembic:/app/alembic
      - ../data:/app/data
    command: tail -f /dev/null
    networks:
      - pydigestor-network

networks:
  pydigestor-network:
    driver: bridge
